In [1]:
import joblib
import numpy as np

import pandas as pd 
from matplotlib import pyplot as plt 
import hist 

In [2]:
data1516 = joblib.load("/global/cfs/projectdirs/atlas/hrzhao/HEP_Repo/QG_Calibration/NewWorkflow/trained_lightGBM_new/nominal/data1516_pred.pkl")

In [14]:
_hist = hist.Hist(hist.axis.Regular(bins=60, start=0, stop=60, name="jet_nTracks"), storage=hist.storage.Weight())

In [15]:
_hist.fill(data1516["jet_nTracks"], weight=data1516["event_weight"])

Hist(Regular(60, 0, 60, name='jet_nTracks'), storage=Weight()) # Sum: WeightedSum(value=1.88869e+07, variance=1.88869e+07) (WeightedSum(value=1.88924e+07, variance=1.88924e+07) with flow)

In [16]:
_hist.reset()
_hist.fill(data1516["jet_nTracks"], weight=data1516["jet_nTracks_quark_reweighting_weights"])

Hist(Regular(60, 0, 60, name='jet_nTracks'), storage=Weight()) # Sum: WeightedSum(value=1.95164e+07, variance=2.0336e+07) (WeightedSum(value=1.9522e+07, variance=2.03416e+07) with flow)

In [8]:
forward = data1516[data1516["is_forward"]==1]
central = data1516[data1516["is_forward"]==0]

central_500 = central[central["pt_idx"]==0]

In [9]:
reweight_factor = joblib.load("/global/cfs/projectdirs/atlas/hrzhao/HEP_Repo/QG_Calibration/NewWorkflow/trained_lightGBM_new/nominal/reweight_factor.pkl")

In [13]:
reweight_factor_pt_var_quark = reweight_factor[500]["jet_nTracks"]["quark_factor"]

In [18]:
hist_ntrk_500_central = hist.Hist(hist.axis.Regular(bins=60, start=0, stop=60, name="jet_nTracks"), storage=hist.storage.Weight())
hist_ntrk_500_central.fill(central_500["jet_nTracks"], weight=central_500["event_weight"])

Hist(Regular(60, 0, 60, name='jet_nTracks'), storage=Weight()) # Sum: WeightedSum(value=4.60913e+06, variance=4.60913e+06) (WeightedSum(value=4.6095e+06, variance=4.6095e+06) with flow)

In [19]:
hist_ntrk_500_central_weighted = hist.Hist(hist.axis.Regular(bins=60, start=0, stop=60, name="jet_nTracks"), storage=hist.storage.Weight())
hist_ntrk_500_central_weighted.fill(central_500["jet_nTracks"], weight=central_500["jet_nTracks_quark_reweighting_weights"])

Hist(Regular(60, 0, 60, name='jet_nTracks'), storage=Weight()) # Sum: WeightedSum(value=4.95392e+06, variance=5.4017e+06) (WeightedSum(value=4.95428e+06, variance=5.40206e+06) with flow)

In [23]:
hist_ntrk_500_central.values() * reweight_factor_pt_var_quark

array([0.00000000e+00, 0.00000000e+00, 2.73567589e+03, 6.58030452e+03,
       1.47913167e+04, 2.89630479e+04, 4.93818163e+04, 7.45790333e+04,
       1.01041834e+05, 1.27804002e+05, 1.51093116e+05, 1.72362289e+05,
       1.89029961e+05, 2.03644263e+05, 2.14522889e+05, 2.23956868e+05,
       2.28878896e+05, 2.32888786e+05, 2.33968550e+05, 2.33347941e+05,
       2.27679910e+05, 2.17674197e+05, 2.09756847e+05, 2.00878991e+05,
       1.87606916e+05, 1.75430381e+05, 1.59890068e+05, 1.46812712e+05,
       1.31040364e+05, 1.18715758e+05, 1.04943106e+05, 9.10773800e+04,
       7.91666720e+04, 6.85481022e+04, 5.98293977e+04, 5.02901197e+04,
       4.31023739e+04, 3.55681466e+04, 3.08582144e+04, 2.44950575e+04,
       1.96075792e+04, 1.72627074e+04, 1.36766634e+04, 1.08637858e+04,
       8.86427339e+03, 6.76602795e+03, 5.95290157e+03, 3.97696058e+03,
       3.60056196e+03, 3.05504503e+03, 1.68588220e+03, 1.47119548e+03,
       1.28060761e+03, 9.56357466e+02, 7.77173772e+02, 3.20484579e+02,
      

In [25]:
hist_ntrk_500_central_weighted.values()

array([0.00000000e+00, 0.00000000e+00, 2.73567589e+03, 6.58030452e+03,
       1.47913167e+04, 2.89630479e+04, 4.93818163e+04, 7.45790333e+04,
       1.01041834e+05, 1.27804002e+05, 1.51093116e+05, 1.72362289e+05,
       1.89029961e+05, 2.03644263e+05, 2.14522889e+05, 2.23956868e+05,
       2.28878896e+05, 2.32888786e+05, 2.33968550e+05, 2.33347941e+05,
       2.27679910e+05, 2.17674197e+05, 2.09756847e+05, 2.00878991e+05,
       1.87606916e+05, 1.75430381e+05, 1.59890068e+05, 1.46812712e+05,
       1.31040364e+05, 1.18715758e+05, 1.04943106e+05, 9.10773800e+04,
       7.91666720e+04, 6.85481022e+04, 5.98293977e+04, 5.02901197e+04,
       4.31023739e+04, 3.55681466e+04, 3.08582144e+04, 2.44950575e+04,
       1.96075792e+04, 1.72627074e+04, 1.36766634e+04, 1.08637858e+04,
       8.86427339e+03, 6.76602795e+03, 5.95290157e+03, 3.97696058e+03,
       3.60056196e+03, 3.05504503e+03, 1.68588220e+03, 1.47119548e+03,
       1.28060761e+03, 9.56357466e+02, 7.77173772e+02, 3.20484579e+02,
      

In [28]:
np.allclose((hist_ntrk_500_central.values() * reweight_factor_pt_var_quark),hist_ntrk_500_central_weighted.values())

True

In [29]:
joblib.load("/global/cfs/projectdirs/atlas/hrzhao/qgcal/Samples_Dec11/pythia/pythiaA_hist/SumofWeights_A.pkl")

array([9.60340000e+07, 1.68158606e+04, 1.73514685e+02, 1.40059219e+01,
       1.31401094e-01, 9.53733236e-03, 3.02887896e-03, 8.73200652e-04,
       1.47115647e-04])

In [30]:
joblib.load("/global/cfs/projectdirs/atlas/hrzhao/qgcal/Samples_Dec11/pythia/pythiaD_hist/SumofWeights_D.pkl")

array([1.98630000e+07, 3.66271396e+03, 1.45318847e+02, 4.44990150e+00,
       1.66390557e-01, 1.37993879e-02, 3.82368959e-03, 1.10434092e-03,
       2.14897899e-04])

In [31]:
joblib.load("/global/cfs/projectdirs/atlas/hrzhao/qgcal/Samples_Dec11/pythia/pythiaE_hist/SumofWeights_E.pkl")

array([9.23090000e+07, 8.43519920e+03, 1.88737963e+02, 1.91043535e+01,
       3.46616910e-01, 3.89311047e-02, 5.33351928e-03, 1.53889750e-03,
       2.74863663e-04])